#ENC[AES256_GCM,data:XZEcHJXNVclCOVTjSPvZ50957GExSLwwK62/UF+7ciFkTYbZ,iv:e/I/LBF2n5C84/3IHddTrEPplCKGZd5aspMLlWF2itY=,tag:3fhiMcxn4cpmLeum1rNd3Q==,type:comment]
#ENC[AES256_GCM,data:vDV55wWDlmvuR+VqgNpIWEV9N2MCzB+ePkt8aU2lb3zAPVlHaRAQnELsFizMHZ+l/2XJ+uHBbkK1FO+CHlUk6CY=,iv:TJlvU+LvrQHl4kh9If/shpEqrn7lwg/J8uvs/cBraGI=,tag:UhHAazv91u01dsRYyafU9g==,type:comment]
#ENC[AES256_GCM,data:80qGkCSCSIfrdTkfWn9Hyc1q+sgeTkN9Bt7KtvKzvQsMgwK+YlxfBZaqp/6T1aZeqGtB,iv:v2UpzbbnfbVE5bDaxahC24AS5dwX2YdLkNoBL4WCiF8=,tag:hV9/EfnmHCVs2R+m6MycOg==,type:comment]
#ENC[AES256_GCM,data:ivuqaL42WPnCKX62yGET5ilpQXs=,iv:GrBRsjFldgWysW5KnIgCB/7WpA//gGUdBzO/56aXDGU=,tag:g1sHaTQuWcijMkGhUuCMOw==,type:comment]
postgres_password: ENC[AES256_GCM,data:stJyC0+nyal7sbXG4DTVFsJVCRxtWXtoCVLJ,iv:rMXjTpgrtWMP1N9d/+K1uyyQa26OYUbshbPZiusx7UI=,tag:FRhfRQ+gIwbYd6EFuF1Srg==,type:str]
web_username: ENC[AES256_GCM,data:P84XaeQ=,iv:Lxwy6xgm77Ocg/7VcpLxsDkxqBAEFbM7WkwUwC3RohQ=,tag:kCCb7zr8JApUpDvrJ5Ch6g==,type:str]
web_password: ENC[AES256_GCM,data:vYew3wSzvZtg0/oRV22jlNK1qTL7eQ==,iv:yM32nfK7ig9qndMkjdjILcjblNjYpp5fCii8QGeUUBI=,tag:A15HggcYd0Guc9+G0w7xTg==,type:str]
session_secret: ENC[AES256_GCM,data:r6uPKQOzdCM0xMjc1fp/bGiAxLY0GRBnumLZtXIrpVOo,iv:bWxPfmlfsq9nZkBOH+aHng+xL1veSogJymHXiQKUpSQ=,tag:ykm3QlgVkUit3GXikGR/ZA==,type:str]
dashboard_api_key: ENC[AES256_GCM,data:X60TQgJATfw66iMWvZrRdrYP+BsfA3HruJNAxID/oID0np/1,iv:y/5c2CONJfyaet/ySwT2iRPb2N06IcEkYPY+bz62l+A=,tag:SzeKEY0NAmjekseMXBxRpg==,type:str]
service_auth_token: ENC[AES256_GCM,data:zSAW1oM+3JRZxyGmFA/yVFwMdScLINylKNHX1qyThTNT9IfzLw==,iv:/bap51QJuNLGvhaYbzW2A2HBvjuhOJ8Q5VZYlb84fMs=,tag:8QLQuRxUH25JtwXvygxVmA==,type:str]
flask_secret_key: ENC[AES256_GCM,data:mUjqmWVsNe4vQ3HRfR7MspIdbjmNIf71YIu+3sN5v/cX2eA=,iv:IvPIPJjM+R0vspvc61m6Ck+NH6XKkNUHUnLzDdXMNDo=,tag:Nw9POnlDXA7oB3ZB3E44AQ==,type:str]
#ENC[AES256_GCM,data:KDSFtwWZXHGCKtDlkoPwwfgPQw==,iv:HGgQamKvUE7qadRV4j/+S0m6bqr1e8u8fbmwTjx9kps=,tag:JoGKc20MTtLX9mlqUw5Dvg==,type:comment]
discord_db_password: ENC[AES256_GCM,data:MlM2TlCcryjblNonCkYC6cUwum+C3cWSFB7L4OE=,iv:47U3p7GDYbe7DKnOmuqVahf0SsClMoD+TWoiNHnLHQc=,tag:HKiz8sPLp1jbefUa7jEaLQ==,type:str]
streambot_db_password: ENC[AES256_GCM,data:qvN/3Y8orqy227RhS1Lit9bcPgx3YqOUaJqy+ejx2w==,iv:42nniMhcKW/qIuIbudwQb5bBjNihjOeZxpatiWiN0EA=,tag:4+BvhM3tEjCQcFukX2lfoQ==,type:str]
jarvis_db_password: ENC[AES256_GCM,data:1HlFgVKARDVJx40GmZh1vvdAlg1/5ViypjA9IQ==,iv:3amDetio7FYS5U6n1hUsb2GxH13Dee+WWXcL74wqAiE=,tag:i90pqr9CVQ7Er2hURVvguQ==,type:str]
#ENC[AES256_GCM,data:4QS3q6aWbOyAZauN,iv:wp1XGJDd6ndkNrywQ8UBZJ5bYXNGr7C2bxNcdxJjaMU=,tag:emnksYfO/8rBrBNSfAnCUQ==,type:comment]
openai_api_key: ENC[AES256_GCM,data:zEYZHt+7DjJhDNh9JVGBXoV6wboAOtqkaC9LDiKwk0U=,iv:3xwDj2weDfk5TM0CtJQgAw0SXbOg1lbsPvdbFJqfRDI=,tag:i10VxSooinvA/kPDwbrynA==,type:str]
#ENC[AES256_GCM,data:NJEOGtLltHnWr2C8AE4lTdLsNA==,iv:3NQnBdlTezTOsPS+pVIOeFsWqKEcmzAh6pGFkRjX+Ds=,tag:SJXnsaEfqa0QBC4Wvidb/A==,type:comment]
streambot_session_secret: ENC[AES256_GCM,data:48r+QSxl8JbLL477d4gWM5ksIHsP8j+w+7qVYw0p/uICkA==,iv:AjuCCp8DwUgOLaiZTe+MsIUDHMAryIzSEOHGeC0WUu4=,tag:AXlbPJ7tSomy5toLv9mJ/Q==,type:str]
#ENC[AES256_GCM,data:xboadHT0fOduhHI/,iv:vWhplTpinWL05wC14GABmdxATHoDyu4OLUDwKDruhrk=,tag:k931e18QCJKyyGVxgT4IuQ==,type:comment]
discord_bot_token: ENC[AES256_GCM,data:hTKsQmbmjJQbVLovxHWdCCGscN6jQ0xazm67,iv:bT5is0NydrxFCZk3G94xysQaNj/d43KRroZuKUPvJAk=,tag:Qyej/jk/ptq5J4BvIu2DGw==,type:str]
discord_client_id: ENC[AES256_GCM,data:tspeYUMueIoiORzQutqG53deUmmgVLmg5gGq,iv:jynNEoZF+oY+ryfNa+QsDCCSabNrqBz7DPL1n8lUE6k=,tag:Ffd3cCCLMgZwsWd8fHvlxA==,type:str]
discord_client_secret: ENC[AES256_GCM,data:Uw5gmUplNi9fgI2K6iNP7EwfqY+dy05ovne5WoCymg==,iv:wOtqDKFLwYODmXWyMrfaZ7Ei1nrTiZZu1CHAJBqBQDY=,tag:vfa/82Tfjn5QgCNA5nZwbA==,type:str]
discord_app_id: ENC[AES256_GCM,data:V8PGgsga/um3KU7D6Cy13gS4b29Fj3vF,iv:5Uv2cmOHsrcmC1bo/FM9uAc5+pyZvkCGpb+O0v4C4ig=,tag:buAlvLJuBOohTCU4Dcegqw==,type:str]
discord_session_secret: ENC[AES256_GCM,data:GP/UajBDt4uETt0l/R3dZOMvXKbDK0fuQNivU7s9w+E=,iv:SLX7+EUHpFrVGDPSdj0cysr2QxygD185LZrUv85glN4=,tag:evrsaaWVfl9YBLjUZ5RCEA==,type:str]
#ENC[AES256_GCM,data:Mgw1aC/A1YHgq1NSLCI0gUXp5MMLxAdO1ms8kSdn,iv:J3GOTV9DWdku3zgRl6KjbzyiIiBCtOFM6FJc/0jSXME=,tag:0LyOAME77bj1n42Y7rWGHw==,type:comment]
twitch_client_id: ""
twitch_client_secret: ""
twitch_channel: ""
#ENC[AES256_GCM,data:O9yJcbJtldIYeEVifMJueBSJEL4=,iv:sRhHL0l79m7H2XWEBn/IlG8WTK+wazV/7E7nV66xSPA=,tag:+NyKg3Ab9zV3/tkSzYkyZw==,type:comment]
youtube_client_id: ""
youtube_client_secret: ""
youtube_refresh_token: ""
#ENC[AES256_GCM,data:ohqNCL+br7xLbSKo5SNEZD74NYdrYSM0STqGqpG/NQ==,iv:odS7MSV7WDC3VHYj0WO5vSl8Z4gPZ+zWq/lie3hw+sA=,tag:zGOeQ38QuROZx2R0XZSKjQ==,type:comment]
spotify_client_id: ""
spotify_client_secret: ""
spotify_refresh_token: ""
#ENC[AES256_GCM,data:93GPnnUmN3ZqThb2UXToYqa0Sy7qUrjAFgvQTA==,iv:Pa/LuuttaYprEK4fRof8HqmU7MDOHKdx5VHSP+yUexc=,tag:VDYmz58vyisdPr/dYBXFhQ==,type:comment]
kick_client_id: ""
kick_client_secret: ""
#ENC[AES256_GCM,data:XVxSJi8=,iv:J8chcbfltvFWxy3DnLRja3MhWB7XUkz7861XkJiR/ac=,tag:yy22fI3Ktn8xiFpFoIUL1g==,type:comment]
plex_token: ""
plex_claim: ""
#ENC[AES256_GCM,data:U8uBbnSf5sS7WC2W4p9CaWPKhkvSJpjJuts=,iv:q2/SYgcJLxx7ty+LsMclv623EGZ6Ry+UrcTd5S9rTu4=,tag:uIZXlu33kuJ6ud4Z7pXU4Q==,type:comment]
nas_ip: ENC[AES256_GCM,data:a46tvfpqALnqnIaUoA==,iv:eVXTeTp6U0tJQNPkehFu5lRnVoHPn5x7zdsjVc931y8=,tag:QuRXhYprltX8UcUq/6TFOQ==,type:str]
nas_password: ""
#ENC[AES256_GCM,data:1ePp1ySnYc1vcoPP65u0Dd7W5hO5,iv:3DGNFNW3PPtsTtxbKueV5jUjlOlyTSA2BoaOgkefrpc=,tag:wrhPGyC+qAjsyLZjTpmf4Q==,type:comment]
minio_root_user: ENC[AES256_GCM,data:i127Q5A=,iv:0MyWFm5duJdrZlwFr0yB9hQ8kAo9jm+MXmkiUmtSlXE=,tag:fnIz1RltOfRq8Dwq4Cvg4A==,type:str]
minio_root_password: ENC[AES256_GCM,data:wJHV79mGh1XyGoAE0lLA9qbRuiddRLFk,iv:xlBCZFDZ56j+4lkabLvnJpw6oucWFsq3pg5SiuUliqo=,tag:W2Sliol5KZOE8gjahLB0Gw==,type:str]
#ENC[AES256_GCM,data:BIb6naLF7Lj+yu03,iv:Rt5G/W7vS+ePUYdcxVoXcQm2g9t47+08Rav4zGGxQGk=,tag:jemt8BvsBqua6oCNtPyq+Q==,type:comment]
vnc_password: ENC[AES256_GCM,data:ftZeUJYDawPJ5IJ9brEHcM7SyZ0f4Q==,iv:HoK7yuKEp4ki8EtbukoX5QA1ATq9Cz8ZvUlwTQRSLSA=,tag:iE/4nAn62/8lq+525rDtBA==,type:str]
vnc_user_password: ENC[AES256_GCM,data:29LPOO8+VgS7B6r8P039nP3VPds6+u/1Akno,iv:aTvW5jYbt0qk4HWqR1lCdvHvd6+Lw/GeHSvjTheKGzw=,tag:wxSGjiZVMs38QmqJlCVxgg==,type:str]
#ENC[AES256_GCM,data:+KwX8IEMZIGCcbGH,iv:kTwPJ/ORKZCJLLcdwtrOb+BI+QBLX58RayTASMDaKGA=,tag:9/183n/STrXtOEq5FqKG/g==,type:comment]
code_server_password: ENC[AES256_GCM,data:/9fKN482knhjPQBia4va7tHO2MxSpOLZTAfbBHbV,iv:dwAUexgBC98RI8d9Ku6eDBRRdWDY0T6AV35McIzrYDc=,tag:zZO4nwLyYIRRALiILqdSRQ==,type:str]
#ENC[AES256_GCM,data:eka57nidkl7z/Zg1uz2ADcF8g311j3p8BLs=,iv:hrKmY+AXKrJifzknOkU0YJAho3fMOZpUR4aM4gBG4Kc=,tag:WH1ZSMSc6kfJZaQ5u47GEw==,type:comment]
home_assistant_token: ""
#ENC[AES256_GCM,data:FDEWciVnulwT6goSNJktavzmsxk=,iv:zpM8GpADL69GOggUXux5XlhrRqv9IaJR8c1OrnlrMsM=,tag:3r55jeUL3DBxumbybx4EmA==,type:comment]
letsencrypt_email: ENC[AES256_GCM,data:uJEwVbKpoHeOuFU65k0j0Y8LjvPFLA==,iv:wFkYhqr2cAIHSqVebb3+r+EKlCdrZfNm99WE/14Kfkk=,tag:FdHp2XZpKY/OxW9hR3UJDg==,type:str]
gmail_default_recipient: ENC[AES256_GCM,data:yXOvxeACBTK8pRiuqXnwIUvYFpJ38w==,iv:NRNKueuM6RCTkPQoBus0P6kofGW3wyswah/6i3dSXe0=,tag:74PV1DKjBUACb3WOdouWwA==,type:str]
sops:
    age:
        - recipient: age1waux0xs07gnp50xspsspxksvkxdmxfywtj5699ck4kcvcs56rdesdmgclr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMFRPOWx2Z3M3Z2t0a3pt
            QjZ0MSt2ei9veENBQU1ETlBTc0p1eG1wVDA4Cjd4WFh0NFpkbFArdEJUNktXNlFC
            Yk1PdXFOOXByRmhHS2cxSUVkOUg4RTAKLS0tIGlYMWVDSkVBQzN0THBtcDZ5TWNF
            KzlXWGVtWkVKcVlvZ21BSlMxYnRnN1UKIp5H3XVxJRMt0xBXbRZvSkQ18mQZADTK
            lool1wvkgBT3SnHg9pkKKEwh56FeXv8Qw5C13BFFuMzUk05WLpqsCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T15:35:07Z"
    mac: ENC[AES256_GCM,data:1IwBwyLAFjk59tqApxE+4zvFPpxmG+TIaTBKTM5AfAXjYPTKRsod8BmJ72mjOZ/vGUkLPUgThHoeHlGEg2ana/5o7VzuyafosOsH4V/X6aOl4/m00XqzrgqiKvL9o2mvZzKSz7nlLwTEtLbW3fuYgZL+uovmMYTHu5dRIDvOzD4=,iv:8uscYg0kRBsVdqjNr1i+Uo86R/yAr+6lzdb4ma2hL3c=,tag:Inonn/+wFoVT+195PjN+gQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
